### ISSUE TITLE
setup.py dependency error

### ISSUE THREAD

**Issue by Salvatore-tech** [neu-vi/ezflow#236]
Good evening, i created a conda env thorugh `conda env create -f environment.yml` and then activated it.
However when i try to `python setup.py install/develop` i get the following message:
```
Installed /home/s/FlowNets/ezflow
Processing dependencies for ezflow==0.2.3
error: importlib-metadata 4.11.4 is installed but importlib-metadata<1,>=0.12; python_version < "3.8" is required by {'tox'}

```

Can you please clarify what's wrong?
Thanks in advance

**Comment by NeelayS** [comment]
Hi @Salvatore-tech, thanks for your interest in `ezflow` and sorry for the error you encountered. I've pushed a fix for this error in #238. Could you please try installing the library once again without creating a conda env thorugh `conda env create -f environment.yml`? Thanks.

Also, if you wish, you can also install a stable release of the library using `pip install ezflow`.

If you face any further trouble, please feel free to comment here. Hope you'll like using the library.

**Comment by Salvatore-tech** [comment]
Hi @NeelayS, thanks for the answer, after the https://github.com/neu-vi/ezflow/pull/238 the install process for stable release is fixed, but if i try to compile from source (`python setup.py install`) it gives a new conflict about Pillow:
`error: Pillow 8.3.1 is installed but pillow!=8.3.*,>=5.3.0 is required by {'torchvision'}`

Can you verify if the conflict exists? Thanks!

**Comment by NeelayS** [comment]
> Hi @NeelayS, thanks for the answer, after the #238 the install process for stable release is fixed, but if i try to compile from source (`python setup.py install`) it gives a new conflict about Pillow: `error: Pillow 8.3.1 is installed but pillow!=8.3.*,>=5.3.0 is required by {'torchvision'}`
> 
> Can you verify if the conflict exists? Thanks!

Hi @Salvatore-tech, did try installing in a new but empty virtual environment (conda/venv)? 

To check, I also tried installing the library in a [Colab notebook](https://colab.research.google.com/drive/1vHmB9KQi0aYlhK31fAPmjWbWsgTb2-LF?usp=sharing) and that works fine.

**Comment by Salvatore-tech** [comment]
I tried again creating a new conda empty environment with python 3.8 but i'm getting the following error   
 `error: numpy 1.23.2 is installed but numpy<1.23.0, >=1.16.5 is required by {'scipy'}`

**Comment by NeelayS** [comment]
> I tried again creating a new conda empty environment with python 3.8 but i'm getting the following error `error: numpy 1.23.2 is installed but numpy<1.23.0, >=1.16.5 is required by {'scipy'}`

Could you please provide the complete error trace?

**Comment by Salvatore-tech** [comment]
I'm closing the issue since i'm not able to reproduce it anymore :) 
Probably i messed up with the global version of numpy or something like that, because it was complaining about the fact that numpy was already installed but with a not suitable version.
Thanks for your support!
